services:
  dev:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=lambda,apigateway
      - DEBUG=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../artifact:/workspace
      - ../init:/etc/localstack/init/ready.d
    working_dir: /workspace